export { default as ProgressBar } from './ProgressBar.vue'
export { default as ToolTips } from './ToolTips.vue'
export { default as Test } from './Test.vue'
export { default as Transform } from './Transform.vue'
export { default as Experince } from './Experience.vue'
